name: Build and Update on production

on:
  push:
    branches: ["main"]

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit

  dispatch:
    name: Dispatch to acm-aws
    needs: build
    runs-on: ubuntu-latest
    environment: Production
    concurrency: Production
    steps:
      - name: Dispatch workflow
        uses: diamondburned/acm-aws/.github/actions/update-pkg@main
        with:
          token: ${{ secrets.PAT_TOKEN }}
          package: sendlimiter
